spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: delivery_schema
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/delivery-db
    username: postgres
    password: ${DB_PASSWORD:shareit}

server:
  port: 0

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.datasource.init: DEBUG

feign:
  client:
    config:
      warehouse:
        connectTimeout: 5000
        readTimeout: 5000
      order:
        connectTimeout: 5000
        readTimeout: 5000

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

delivery:
  calculation:
    fragile-multiplier: 0.2
    weight-multiplier: 0.3
    volume-multiplier: 0.2
    address-multiplier: 0.2
  warehouse:
    address-1-multiplier: 1.0
    address-2-multiplier: 2.0